#!/usr/bin/sh

set -e

slug() {
  iconv -t ascii//TRANSLIT | sed -r 's/[^a-zA-Z0-9]+/-/g' | sed -r 's/^-+|-+$//g' | tr '[:upper:]' '[:lower:]'
}

([ "$#" -eq 1 ] && (sed -n 's/^title:\s*\(.*\)$/\1/p' "$1" | slug)) || slug
